# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6f018cdb02e4ad67ac9965a25bd54e5f959b61a2b6b6a2c61409370dfdc2f7339aaa9e173f91d8cf9bde61f870e671443df35f4454b541ab8229f4a7ed9da24c

test:
  secret_key_base: e6058ae504200d31bce3b9722aad6717e4681ecfbd013dda8147117ddea39ae74432ecc040ca4aa83f27253ad90b746eb45a1c471890e0c9ed14b9c15803fbcc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
